# compose: dc-atualiza-membros.yaml

networks:
  atualiza_membros:
    name: atualiza_membros

services:
  db_atualiza_membros:
    image: mariadb:latest
    container_name: db_atualiza_membros
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${ROOT_DIR}/database:/var/lib/mysql
    restart: no
    networks:
      - atualiza_membros

  app_atualiza_membros:
    image: atualiza-membros-app:1.0
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: atualiza_membros.dockerfile
    container_name: app_atualiza_membros
    env_file:
      - .env
    volumes:
      - ${ROOT_DIR}/app:/var/www/html
    ports:
      - "8085:80"
    restart: no
    networks:
      - atualiza_membros
    depends_on:
      - db_atualiza_membros
